import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('file command authentication, ownership, paths, transfer verification and replay', async () => {
  const db = new PGlite();
  const own = '11111111-1111-4111-8111-111111111111', other = '22222222-2222-4222-8222-222222222222';
  const hash = 'a'.repeat(64), storage = `${own}/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/payload`;
  try {
    await db.exec(`create role anon; create role authenticated; create role service_role;
      create schema auth; create schema storage;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth,public,storage to anon,authenticated,service_role;
      grant execute on function auth.uid() to anon,authenticated,service_role;
      create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
      create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
      alter table storage.objects enable row level security;
      grant select,insert,update,delete on storage.objects to authenticated;
      create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;
      insert into auth.users values('${own}'),('${other}');`);
    for (const name of ['202609200001_link_cloud.sql', '202610030001_file_commands.sql', '202610030002_remote_commands.sql']) await db.exec(await readFile(new URL('../supabase/migrations/' + name, import.meta.url), 'utf8'));
    await db.exec(`insert into private.link_members values('${own}'),('${other}')`);
    const role = async (r, user='') => db.exec(`reset role; set role ${r}; select set_config('request.jwt.claim.sub','${user}',false)`);
    const rpc = async (name, args) => (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args)).rows[0].result;
    await role('authenticated', own);
    const device = await rpc('link_register_device', ['Test','ESP32-S3']);
    const cmd = (action, payload={}) => rpc('link_device_command',[device.device_id,device.token,action,payload]);
    const queue = (op,path,resource=null,cursor=0) => rpc('link_queue_command',[device.device_id,op,path,resource,cursor,false]);
    await assert.rejects(cmd('command_claim'), /permission denied/);
    await assert.rejects(db.query('insert into link_commands(owner_id,device_id,op,path) values($1,$2,$3,$4)',[own,device.device_id,'mkdir','/x']),/permission denied/);
    for (const path of ['/../secret','/x/../y','/.LINK/private','/x//y','/x/','/x./y','/x /y','/x\\y','/x:y','/x\n']) await assert.rejects(queue('mkdir',path),/Invalid command/,path);
    await assert.rejects(queue('put','/'),/Invalid command/);
    await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['link-resources',storage,{size:0}]);
    await assert.rejects(rpc('link_register_file',[storage,'empty.bin',null]),/Invalid file/);
    const file = await rpc('link_register_file',[storage,'empty.bin',hash]);
    const put = await queue('put','/empty.bin',file);
    await role('authenticated', other);
    assert.equal((await db.query('select * from link_commands')).rows.length,0);
    await assert.rejects(queue('get','/empty.bin'),/not owned/);
    await role('service_role');
    await assert.rejects(rpc('link_device_command',[device.device_id,'b'.repeat(64),'command_claim',{}]),/Unauthorized/);
    assert.equal((await cmd('command_claim')).command.id,put);
    assert.equal((await cmd('command_claim')).command.id,put);
    await assert.rejects(cmd('command_result',{id:put,status:'completed',bytes:1,sha256:hash}),/verification/);
    await assert.rejects(cmd('command_result',{id:put,status:'completed',bytes:0,sha256:'b'.repeat(64)}),/verification/);
    await cmd('command_result',{id:put,status:'completed',bytes:0,sha256:hash});
    assert.equal((await cmd('command_result',{id:put,status:'completed',bytes:0,sha256:hash})).status,'completed');
    await role('authenticated',own);
    const listing = await queue('list','/novels');
    await role('service_role'); await cmd('command_claim');
    for (const result of [null,{}, {entries:[]}, {entries:[],cursor:0,end:false}]) await assert.rejects(cmd('command_result',{id:listing,status:'completed',result}),/Invalid/);
    await cmd('command_result',{id:listing,status:'completed',result:{entries:[],cursor:0,end:true}});
    await role('authenticated',own);
    const get = await queue('get','/novels/book.txt');
    await role('service_role'); assert.equal((await cmd('command_claim')).command.id,get);
    await assert.rejects(cmd('command_result',{id:get,status:'completed',bytes:3,sha256:hash}),/Upload not complete/);
    await db.exec('reset role');
    await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['link-resources',`${own}/${get}/payload`,{size:3}]);
    await role('service_role');
    await cmd('command_progress',{id:get,bytes:2});
    await assert.rejects(cmd('command_progress',{id:get,bytes:1}),/Invalid progress/);
    await cmd('command_result',{id:get,status:'completed',bytes:3,sha256:hash});
    await cmd('command_result',{id:get,status:'completed',bytes:3,sha256:hash});
    await role('authenticated',own);
    const row=(await db.query('select * from link_commands where id=$1',[get])).rows[0];
    assert.ok(row.result.resource_id);
    assert.equal((await db.query('select * from link_resources where storage_path=$1',[`${own}/${get}/payload`])).rows.length,1);
    const cancel=await queue('mkdir','/empty-folder'); await rpc('link_cancel_command',[cancel]);
    await role('service_role'); assert.equal((await cmd('command_claim')).command,null);
    await role('authenticated',own);
    const remote = (op,path='/',args={}) => rpc('link_queue_remote',[device.device_id,op,path,args]);
    await assert.rejects(remote('music.volume','/',{volume:101}), /Invalid volume/);
    await assert.rejects(remote('music.play','/novels/book.txt'), /Invalid music/);
    await assert.rejects(remote('music.stop','/',{op:'put'}), /Invalid arguments/);
    const volume = await remote('music.volume','/',{volume:42});
    await role('service_role');
    const claim = (await cmd('command_claim')).command; assert.equal(claim.id,volume);assert.equal(claim.volume,42);
    await cmd('command_result',{id:volume,status:'completed',result:{accepted:true,completion:'accepted'}});
    await role('authenticated',own);
    const playing = await remote('music.status');
    await role('service_role');await cmd('command_claim');await cmd('command_result',{id:playing,status:'completed',result:{state:'Playing'}});
    await role('authenticated',own);
    const running=await queue('mkdir','/a');
    await role('service_role'); await cmd('command_claim');
    await role('authenticated',own); await assert.rejects(rpc('link_cancel_command',[running]),/Only waiting/);
    await role('service_role'); await cmd('command_result',{id:running,status:'failed',error:'SD_BUSY'});
    assert.equal((await cmd('command_claim')).command,null);
  } finally { await db.close(); }
});
